# -*- coding: utf-8 -*-
"""Copia de D2 Introducción a Tests Estadísticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JYRAI-qe0gln8_ao_vK3swhK8QwA61xn
"""

import pandas as pd 
tmdb = pd.read_csv("tmdb_5000_movies.csv")

tmdb.head(2)

tmdb.describe()

import seaborn as sns

ax = sns.distplot(tmdb.vote_average,
             kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

sns.boxplot(tmdb.vote_average)

tmdb_10_o_mas_votos = tmdb.query("vote_count >= 10")
tmdb_10_o_mas_votos.describe()

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average,
             kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.boxplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

notas = pd.read_csv("ratings.csv")
notas.head()

nota_promedio_por_pelicula = notas.groupby("movieId").mean()["rating"]
nota_promedio_por_pelicula.head()

sns.distplot(nota_promedio_por_pelicula.values)

cantidad_votos_por_pelicula = notas.groupby("movieId").count()
cantidad_votos_por_pelicula.head()

peliculas_10_o_mas_votos = cantidad_votos_por_pelicula.query("rating >= 10").index

peliculas_10_o_mas_votos

nota_promedio_por_pelicula_10_o_mas_votos = nota_promedio_por_pelicula.loc[peliculas_10_o_mas_votos.values]
nota_promedio_por_pelicula_10_o_mas_votos.head()

ax = sns.distplot(nota_promedio_por_pelicula_10_o_mas_votos.values)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.distplot(nota_promedio_por_pelicula_10_o_mas_votos.values,
                   kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.boxplot(nota_promedio_por_pelicula_10_o_mas_votos.values)
ax.set(xlabel = "Nota Promedio")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")