# -*- coding: utf-8 -*-
"""Copia de D2 Introducción a Tests Estadísticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vCtXXsJbiF27HjX5aKj4s6-_d51bj8Qq
"""

import pandas as pd 
tmdb = pd.read_csv("tmdb_5000_movies.csv")

tmdb.head(2)

tmdb.describe()

import seaborn as sns

ax = sns.distplot(tmdb.vote_average,
             kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

sns.boxplot(tmdb.vote_average)

tmdb_10_o_mas_votos = tmdb.query("vote_count >= 10")
tmdb_10_o_mas_votos.describe()

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average,
             kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio", ylabel = "frecuencia")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

ax = sns.boxplot(tmdb_10_o_mas_votos.vote_average)
ax.set(xlabel = "Nota Promedio")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

notas = pd.read_csv("ratings.csv")
notas.head()

nota_promedio_por_pelicula = notas.groupby("movieId").mean()["rating"]
nota_promedio_por_pelicula.head()

sns.distplot(nota_promedio_por_pelicula.values)

cantidad_votos_por_pelicula = notas.groupby("movieId").count()
cantidad_votos_por_pelicula.head()

peliculas_10_o_mas_votos = cantidad_votos_por_pelicula.query("rating >= 10").index

peliculas_10_o_mas_votos

nota_promedio_por_pelicula_10_o_mas_votos = nota_promedio_por_pelicula.loc[peliculas_10_o_mas_votos.values]
nota_promedio_por_pelicula_10_o_mas_votos.head()

ax = sns.distplot(nota_promedio_por_pelicula_10_o_mas_votos.values)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.distplot(nota_promedio_por_pelicula_10_o_mas_votos.values,
                   kde = False,
             norm_hist = False)
ax.set(xlabel = "Nota Promedio", ylabel = "densidad")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.boxplot(nota_promedio_por_pelicula_10_o_mas_votos.values)
ax.set(xlabel = "Nota Promedio")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.distplot(nota_promedio_por_pelicula_10_o_mas_votos.values,
                  hist_kws = {"cumulative":True},
                  kde_kws = {"cumulative":True})
ax.set(xlabel = "Nota Promedio", ylabel = "% Acumulado")
ax.set_title("Grafico de distibución del Promedio de notas de Movielens")

ax = sns.distplot(tmdb_10_o_mas_votos.vote_average,
                  hist_kws = {"cumulative":True},
                  kde_kws = {"cumulative":True})
ax.set(xlabel = "Nota Promedio", ylabel = "% Acumulado")
ax.set_title("Grafico de distibución del Promedio de notas de TMDB")

"""#Analizando otras variables"""

ax = sns.distplot(tmdb_10_o_mas_votos.vote_count)
ax.set(xlabel = "Cantidad de Votos", ylabel = "frecuencia")
ax.set_title("Grafico de distibución de la cantidad de votos de TMDB")

ax = sns.distplot(tmdb.query("budget > 0").budget)
ax.set(xlabel = "Presupuesto de las películas", ylabel = "frecuencia")
ax.set_title("Gráfico de distibución del presupuesto de las películas de TMDB")

ax = sns.distplot(tmdb.popularity)
ax.set(xlabel = "Popularidad de las películas", ylabel = "frecuencia")
ax.set_title("Gráfico de distibución de la popularidad de las películas de TMDB")

ax = sns.distplot(tmdb.query("runtime > 0").runtime.dropna())
ax.set(xlabel = "Duración de las películas", ylabel = "frecuencia")
ax.set_title("Gráfico de distibución de la duración de las películas de TMDB")

ax = sns.distplot(tmdb.query("runtime > 0").runtime.dropna(),
                  hist_kws = {"cumulative":True},
                  kde_kws = {"cumulative":True})
ax.set(xlabel = "Duración", ylabel = "% Acumulado")
ax.set_title("Grafico de distibución de la duración de las películas de TMDB")

tmdb.query("runtime > 0").runtime.dropna().quantile(0.8)

"""#Efecto del tamaño de la muestra"""

nota_promedio_por_pelicula_10_o_mas_votos.mean()

len(nota_promedio_por_pelicula_10_o_mas_votos)

nota_promedio_por_pelicula_10_o_mas_votos[0:5].mean()

import matplotlib.pyplot as plt


promedios = list()
for i in range(1,len(nota_promedio_por_pelicula_10_o_mas_votos)):
   promedios.append(nota_promedio_por_pelicula_10_o_mas_votos[0:i].mean()) 

promedios

plt.plot(promedios)

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(75241)
temp = nota_promedio_por_pelicula_10_o_mas_votos.sample(frac=1)
promedios = list()
for i in range(1,len(temp)):
   promedios.append(temp[0:i].mean()) 

promedios

plt.plot(promedios)

"""#Analizando Tests Estadísitcos Z Test - T Test"""

nota_promedio_por_pelicula_10_o_mas_votos.mean()

from statsmodels.stats.weightstats import zconfint

zconfint(nota_promedio_por_pelicula_10_o_mas_votos)

from statsmodels.stats.weightstats import DescrStatsW

descr_notas_10_votos = DescrStatsW(nota_promedio_por_pelicula_10_o_mas_votos)
descr_notas_10_votos.tconfint_mean()

descr_notas_10_votos.zconfint_mean()